# Generated by Django 5.2.5 on 2026-04-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_scan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriftResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=100)),
                ('scenario', models.CharField(max_length=100)),
                ('accuracy', models.FloatField()),
                ('acc_drop', models.FloatField()),
                ('psi', models.FloatField()),
                ('confidence_drop', models.FloatField()),
                ('top_drift_feature', models.CharField(blank=True, max_length=100)),
                ('baseline_accuracy', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
